name: Travelifyv2-Frontend-Dev

# Run the workflow whenever a change is pushed into the feature/deployment-pipelines branch
on:
  push:
    branches:
      - feature/deployment-pipelines
  workflow_dispatch:

# There are two jobs in this workflow - build and deploy
jobs:
  # Builds the application for production
  build:
    runs-on: ubuntu-latest
    environment: Dev
    # Fetch environment variables (secrets) for the build process
    env:
      VITE_BACKEND_URL: ${{ secrets.VITE_BACKEND_URL }}
      VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
      VITE_SUPABASE_CLIENT: ${{ secrets.VITE_SUPABASE_CLIENT }}
      VITE_SUPABASE_SECRET: ${{ secrets.VITE_SUPABASE_SECRET }}
    
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies, build, and test
        run: |
          cd frugaloo
          npm install
          # Make sure that the build process uses the env variables correctly
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: frugaloo/dist
          if-no-files-found: warn

  # Deploy the application to Azure
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production  # Ensure this matches the GitHub environment name

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
          path: ./node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: travelifyv2dev
          slot-name: 'Production'
          publish-profile: ${{ secrets.TRAVELIFY_DEV_FRONTEND_APP }}
          package: ./node-app
